### ISSUE TITLE
Interested in Helping Out

### ISSUE THREAD

**Issue by ChrisOwen101** [Vencorr/Evil-is-Good#3]
Hi! I'm teaching myself Unity at the moment (I have a background in Java and Android Development) and I was thinking about starting a project around Dungeon Keeper and then I found yours and you're actively working on it.

I was wondering if you could let me know the current state of the project (what you've done so far, what you're working on) and how I could help out?

Thanks!

**Comment by Vencorr** [comment]
Hi, thanks for showing interest in the project!

I am also teaching myself Unity. I started this project with many things in mind, but my main priority was to learn Unity Development and C#. I have no background experiences whatsoever as I am only 17 and just now learning. But my main goal for this project is to get it finished, or to a playable state.

I have currently done a small amount of things, as I have recently started fresh as I hope this time a 2nd times a charm. Here are the things I have done so far:
- Created scripts to automatically add fortified objects to both ground and wall
- Created and am currently working on Mark script to signify where to dig
- Made Models for Portal and Dungeon Heart
- Made Models for Fortified Walls
- Made Meshes for Walls, Dirt, and Ground
- Created simple UI for different objects, as well as a minimap

and I cannot think of anything else I have done off the top of my head, or even looking at the project. A lot of things I have "added" from the Unity Asset store for temporary usage and as placeholders to test how the game would react.

Just a warning though, this project is in its very very very early stages. That means there is barely any gameplay besides a few clicks here and there. The UI is very simple and could be improved. The Test map itself is very small, but was created for the sole purpose of testing certain things, and there are no such things as creatures as far as the project is aware.

If you would like to help out, that is much appreciated. Anything could use improvement, and I am always open for suggestions and changes. The project currently uses the latest Beta of Unity3D. I don't know any specifics you could do to help out, but you are free to poke around the project to change what you think is necessary and do what you wish, as long as it isn't malicious.
